apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-project-back
spec:
  selector:
    matchLabels:
      app: cd-project-back
  replicas: 1
  template:
    metadata:
      labels:
        app: cd-project-back
    spec:
      containers:
        - name: cd-project-back
          image: chxws/cd_back:latest
          ports:
            - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  selector:
    app: cd-project-back
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
