apiVersion: apps/v1
kind: Deployment
metadata:
  name: cd-project-front
spec:
  selector:
    matchLabels:
      app: cd-project-front
  replicas: 1
  template:
    metadata:
      labels:
        app: cd-project-front
    spec:
      containers:
        - name: cd-project-front
          image: chxws/cd_front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-svc
spec:
  type: NodePort
  selector:
    app: cd-project-front
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 80
    nodePort: 30000
