---
# tasks file for docker
- name: Create docker image
  docker_image:
    name: cd_front
    build:
      path: /var/jenkins/slave/workspace/cd_project
      pull: 'no'
    source: build
    state: present
    force_source: true

- name: Tag and push to docker hub
  docker_image:
    name: cd_front
    source: local
    repository: chxws/cd_front
    tag: latest
    push: yes
